### ISSUE TITLE
[💡 FEATURE REQUEST]: KV. Ability to see memory statistics

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1412]
### Plugin

KV

### I have an idea!

I use KV memory driver via spiral/roadrunner-bridge. It works but I don't know what happens there.

I need a tool to see statistic about
- memory usage
- keys count
- get\set call in time range
- etc

I suppose it should be some set of RPC methods that can be connected from a birddog or a console command (spiral/roadrunner-bridge)

EDIT:
ref: https://github.com/roadrunner-server/roadrunner/issues/1635

**Comment by rustatian** [comment]
Hey @gam6itko 👋🏻 

- Calculating the memory footprint for the hashmap is not an easy task due to its distributed nature (buckets). I guess that it can be deduced approximately with `unsafe.SizeOf(map)` + len of the map * 8 + size of the key * 8 (keys in the bucket) + size of the value * 8 (values in the bucket).

- Keys count and get/set distribution might be added easily to the `Stat` method. I agree with the keys count, but I don't think the memory driver should have some kind of push per minute (for example) stat (use cases?).
- `etc` ?

**Comment by gam6itko** [comment]
@rustatian 

The main thing that I need is to have info about what is happening in KV.  
At least I need couple of things:
- get total memory usage
- the number of keys

Actually i don't need profiling things like "request per minute" or else. This was written more as an example.

I understand that the RR is not a Redis and I will be happy with the possible minimum of functionality

**Comment by rustatian** [comment]
Nice 👍🏻 
Having some statistics about the in-memory plugin is generally a good idea. It would be planned for the 2023.2.0 milestone (June 2023)

**Comment by rustatian** [comment]
I found a way to calculate a memory consumption (that's not so trivial, since we have to calculate the data size, not the pointers size) of the in-memory driver.

**Comment by rustatian** [comment]
Moving to the `2023.3` release since we don't have any RPC in the KV plugin to check the memory consuption/keys count or other statistic from the driver.
At first, need to create a general RPC in the KV plugin to obtain info from the underlying drivers. Then it would be possible to attach the memory plugin and see statistic from it.
