### ISSUE TITLE
[🐛 BUG]: RR cannot parse larger multipart form data

### ISSUE THREAD

**Issue by FluffyDiscord** [roadrunner-server/roadrunner#1859]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

RoadRunner is unable to parse larger multipart form data.

In my case the whole POST body is around 260KB whoch is not really a lot and contains a moderate amount of inputs. RoadRunner throws error 500 with message `serve_http: multipart: message too large`.

The current workaround is to send JSON instead, but mapping FormData to JSON and back can be prone to errors.

### Version (rr --version)

2023.3.9

### How to reproduce the issue?

[curl.txt](https://github.com/roadrunner-server/roadrunner/files/14136104/curl.txt)

**Comment by rustatian** [comment]
Hey @FluffyDiscord 👋 Thanks for the report 👍 
This issue will be addresses after some HTTP plugin internal updates (move to proto, update multipart algorithm). If that issue is critical for you, you may fork the HTTP plugin and increase this value: [link](https://github.com/roadrunner-server/http/blob/master/handler/request.go#L18) and then build your RR binary with [Velox](https://github.com/roadrunner-server/velox)

**Comment by FluffyDiscord** [comment]
This has not been solved for me. Maybe the issue is that the content-type is `multipart/form-data; boundary=----` ?

**Comment by rustatian** [comment]
Not confirmed as a RR issue. Thread: https://discord.com/channels/538114875570913290/1229393196648366201

**Comment by ismail-ia** [comment]
I'm having the same issue. When I try to submit a request with multiple array input fields that are over 256KB, I get serve_http: multipart: message too large

**Comment by FluffyDiscord** [comment]
It's a bug in Golang I presume. If you are not sending files, use either `application/x-www-form-urlencoded` in body instead or send json, if you can.

**Comment by ismail-ia** [comment]
Thanks! That worked.
