### ISSUE TITLE
[🐛 BUG]: Worker crashed when write logs to stdout

### ISSUE THREAD

**Issue by chris-lee-lb** [roadrunner-server/roadrunner#873]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

we currently use laravel-octane with roadrunner (https://laravel.com/docs/8.x/octane), and we can not write logs to stdout which will make worker crashed.

Here is reproduce repository : 
https://github.com/chris-lee-lb/road-runner-laravel-issues

Startup procedures :

1. composer install
2. ./vendor/bin/sail build --pull
3. ./vendor/bin/sail up -d
4. open browser with `http://localhost`

### Version

2.6.0

### Relevant log output

```shell
worker allocated, pid: 44
worker allocated, pid: 45
error: sync_worker_exec_worker_with_timeout: Network:
	sync_worker_exec_payload:
	goridge_frame_receive: CRC verification failed, bad header: 61b95d551e92b
l���, worker's pid: 44
worker stopped, error: signal: killed; process_wait: signal: killed
```

**Comment by rustatian** [comment]
Hey @chris-lee-lb . Logs are diagnostic information and should be written to the `stderr`. `stdout` and `stdin` process file descriptors are reserved for the RR communication with the worker when you use `server.relay = pipes`.
But, we understand, that for some reason, the users would like to write the logs into the `stdout`. This is allowed after workers are initialized because our [workers](https://github.com/spiral/roadrunner-worker) package redirects `stdout` to the `stderr` without interrupting RR communication channels.
To get your logs in the `stdout` in that case, please, use the `logs.output = stdout` -> [click](https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L102).
Another option is to use `server.relay = tcp`.

**Comment by chris-lee-lb** [comment]
@rustatian Really thanks for your information. After trying `spiral/roadrunner-laravel`, all works very well.

I'll closed it now. Thanks again.

**Comment by rustatian** [comment]
You are very welcome, enjoy using RR 👍🏻
