### ISSUE TITLE
[💡 FEATURE REQUEST]: Split-testing module

### ISSUE THREAD

**Issue by masterjus** [roadrunner-server/roadrunner#950]
### I have an idea!

I have an idea, listen to me!!

Everybody knows about A/B testing. There're few tools like the Google Optimizer which helps to do such tests. 
But sometimes new functionality which need to be tested could be made on a backend only.

We are using the `split_clients` for such tests and this is the inly reason why we're still using nginx before rr.

Here's the source code of the nginx's module https://github.com/phusion/nginx/blob/master/src/http/modules/ngx_http_split_clients_module.c.

As the result, we’d like to route users to different source folders.

We'll be so happy if such plugin would be made for the roadrunner as well.

**Comment by rustatian** [comment]
Hey, @masterjus 👋🏻 Thanks for the FR 👍🏻 

Since RR is not a web-server, I'm not sure, how this feature (or a new plugin) would be implemented in the RR. To have a split-testing feature it's better to use specialized tools, like Nginx, which actually route the requests to the application servers (e.g. RR).
