### ISSUE TITLE
[💡 FEATURE REQUEST]: Consume-only `SQS` driver (or an option to disable queue declaration)

### ISSUE THREAD

**Issue by sergey-telpuk** [roadrunner-server/roadrunner#980]
### Plugin

JOBS

### I have an idea!

I suggest not to allow to create SQS with the help of sqs-plugin. It's just to make connect to aws sqs.

**Comment by rustatian** [comment]
Hey @sergey-telpuk. I'm not sure, that I correctly understand you. Do you mean, connect to SQS and just consume jobs from the queue?

**Comment by sergey-telpuk** [comment]
> Hey @sergey-telpuk. I'm not sure, that I correctly understand you. Do you mean, connect to SQS and just consume jobs from the queue?

Hi, it's

**Comment by sergey-telpuk** [comment]
I don't want to give the control for creating topic RR. It should be the simple consumer

**Comment by rustatian** [comment]
@sergey-telpuk What is the problem with the queue created by RR?

**Comment by sergey-telpuk** [comment]
> @sergey-telpuk What is the problem with the queue created by RR?

1. I have replicas RR, now each of replicas create sqs - it is redundant.
2. I have another tool/operator - that is responsible for creating/updating/deleting sqs. 
3. I have to support duplicates config in RR and my utils.
4. Now RR has bug with attributes cases

**Comment by rustatian** [comment]
1. How do you determine in your replicas, who is responsible to create a queue? This is an idempotent operation AFAIK.
2. This is not a RR responsibility (I mean, other tools)
3. This is also not a RR responsibility to control the third-party utils.
4. Do we have a ticket for that bug?

**Comment by rustatian** [comment]
I understand, that p.2 and p.3 will make your life easier)

**Comment by paulermo** [comment]
There is FR #906 which describes this bug mentioned by @sergey-telpuk. (No way to send attributes of SQS queue to AWS while specifying them in rr.yaml because of lowercasing of yaml keys).
And because of that issue, RR creates SQS queues with some default attributes which can be not suitable for us. When we try to re-create the same queue from operator/another tool - we get an error, cause this operation is idempotent in case of creation with the same attributes only.

**Comment by rustatian** [comment]
> And because of that issue, RR creates SQS queues with some default attributes 

RR doesn't create a queue with default attributes. By default, attributes are null.

**Comment by paulermo** [comment]
Ok, WITHOUT attributes.

And when we try in another place to use same queue but WITH attributes - get an error:

_To get the queue URL, use the GetQueueUrl action. GetQueueUrl requires only the QueueName parameter. be aware of existing queue names:_

_* If you provide the name of an existing queue along with the exact names
and values of all the queue's attributes, CreateQueue returns the queue
URL for the existing queue._

_* If the queue name, attribute names, or attribute values don't match
an existing queue, CreateQueue returns an error._

As a result - we need to ensure that RR does not start (ad does not create queues) until they are created in some other place. And it is not convenient in many cases.

**Comment by rustatian** [comment]
No need to use capslock here, because:

>  RR creates SQS queues with some default attributes

And:

> Ok, WITHOUT attributes.

These are different terms. Please, take a time to think about your problem, and then explain it.

To resolve your problem I need a ticket for it. The ticket you are referencing has the title: `[FEATURE REQUEST]: Support for SQS FIFO queues`. File us a bug with the description of the problem, we will plan it and resolve it. Thanks.

**Comment by paulermo** [comment]
That FR contains the description of a bug which does not let to specify correct sqs attributes from RR.
Ok, if you want me to make a duplicate with a Bug label - I will :)

**Comment by rustatian** [comment]
I don't want duplicates (and this is not a duplicate). As I mentioned, the `Support for SQS FIFO queues` and `Case-Sensitive Attributes` are different terms. I can resolve the case sensitivity problem w/o supporting FIFO queues (yet). So, to summarize:
1. Support for the FIFO - feature request is made.
2. Case-sensitive attributes problem - a separate issue.

**Comment by paulermo** [comment]
For the case sensitivity problem - I've posted separate issue #994.
And regarding the current issue, I'll try to summarize the problem: we propose RR to have the ability to use GetQueueUrl instead of CreateQueue at the start of the worker.

**Comment by rustatian** [comment]
> For the case sensitivity problem - I've posted separate issue #994.

Thank you.

> we propose RR to have the ability to use GetQueueUrl instead of CreateQueue at the start of the worker.

This should be a separate feature request. Because this is suitable for you, but not for all RR users, we can't use `GetQueueUrl` instead of creating a queue, this should be an option in the configuration with the `create queue` as the default behavior (we can't change the default behavior).

**Comment by rustatian** [comment]
@paulermo However, if the `GetQueueUrl` option is more suitable for your, you might close this issue and create a new one with the `GetQueueUrl` FR as the option in the configuration.
